import torch
import torch.nn.functional as F
from typing import Dict, List, Optional


class GCNScorer:
    """
    Compute GCN-based collaborative score for each candidate item.

    Flow:
      1. Retrieve user embedding directly from node_embs (learned by LightGCN)
      2. s_gcn(i) = cosine_sim(h_user, gcn_emb[i])

    Interface:
        scorer = GCNScorer(gcn_embeddings, node_embs, id2name, name2id)
        scores = scorer.score(user_id, candidate_ids)
        # → Dict[item_name, float]
    """

    def __init__(
        self,
        gcn_embeddings: torch.Tensor,             
        node_embs:      Dict[str, torch.Tensor],  
        id2name:        Dict[int, str],
        name2id:        Dict[str, int],
        device:         torch.device = None,
    ):
        self.device = device or torch.device("cpu")

        gcn_emb = gcn_embeddings.to(self.device).float()

        original_norms = gcn_emb.norm(dim=-1)
        self.is_zero_vector = (original_norms < 1e-6)

        norms = gcn_emb.norm(dim=-1, keepdim=True).clamp(min=1e-8)
        self.gcn_norm = gcn_emb / norms             
        self.node_embs = node_embs

        self.id2name   = id2name
        self.name2id   = name2id
        self.num_items = gcn_emb.shape[0]

    def _user_embedding(self, user_id: str) -> Optional[torch.Tensor]:
        u_emb = self.node_embs.get(user_id)
        if u_emb is None:
            return None
        return F.normalize(u_emb.to(self.device).float(), dim=0)  

    def score(
        self,
        user_id:       str,
        candidate_ids: List[int],
    ) -> Dict[str, float]:
        """
        Compute GCN score for each candidate item.

        Args:
            user_id:       Original user ID string (key in node_embs)
            candidate_ids: List of integer item IDs to rank

        Returns:
            Dict[item_name → cosine_score ∈ [-1, 1]]
            Returns score 0.0 for all items if user is cold-start.
        """
        if not candidate_ids:
            return {}

        h_user = self._user_embedding(user_id)

        # Cold-start: user not in graph → uniform score
        if h_user is None:
            return {
                self.id2name.get(cid, f"item_{cid}"): 0.0
                for cid in candidate_ids
                if 0 <= cid < self.num_items
            }

        valid_cans = [
            (cid, self.id2name.get(cid, f"item_{cid}"))
            for cid in candidate_ids
            if 0 <= cid < self.num_items
        ]
        if not valid_cans:
            return {}

        can_ids  = torch.tensor([c[0] for c in valid_cans],
                                dtype=torch.long, device=self.device)
        can_embs = self.gcn_norm[can_ids]              
        sims = (can_embs @ h_user)

        zero_mask = self.is_zero_vector[can_ids]
        sims = sims.masked_fill(zero_mask, -1.0).cpu().tolist()

        return {
            name: float(sim)
            for (_, name), sim in zip(valid_cans, sims)
        }

    def top_k_names(
        self,
        user_id:       str,
        candidate_ids: List[int],
        k:             int = 20,
    ) -> List[str]:
        scores = self.score(user_id, candidate_ids)
        return sorted(scores, key=scores.get, reverse=True)[:k]

    @classmethod
    def from_shared(cls, shared: dict) -> "GCNScorer":
        gcn_emb = shared.get('gcn_embeddings')
        if gcn_emb is None:
            raise ValueError(
                "[GCNScorer] 'gcn_embeddings' not found in shared resources. "
                "Ensure args.gcn_path is set and the file exists."
            )

        node_embs = shared.get('node_embs')
        if node_embs is None:
            import warnings
            warnings.warn(
                "[GCNScorer] 'node_embs' not found in shared resources — "
                "user embeddings will fall back to cold-start (score 0.0). "
                "Use the file generated by remap_gcn_embedding.py for full user embeddings.",
                UserWarning, stacklevel=2
            )
            node_embs = {}

        return cls(
            gcn_embeddings=gcn_emb,
            node_embs=node_embs,
            id2name=shared['id2name'],
            name2id=shared['name2id'],
            device=shared.get('device', torch.device('cpu')),
        )
